id: PC4571158
initial_creation_type: ocr
source_metadata:
  volumes:
    d70e2cdc915c481a9550b98286a0dc5d:
      base_file: v051.txt
      image_group_id: I1PD95896
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་བརྒྱད་སྟོང་པའི་བཤད་པ་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་སྣང་བ།
      total_pages: 1818
      volume_number: 51
